package com.wbg.Excel.entity;

import java.math.BigDecimal;

public class Stu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.s_id
     *
     * @mbg.generated
     */
    private String sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.s_name
     *
     * @mbg.generated
     */
    private String sName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.s_sex
     *
     * @mbg.generated
     */
    private String sSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.s_education
     *
     * @mbg.generated
     */
    private String sEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.s_salary
     *
     * @mbg.generated
     */
    private BigDecimal sSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.s_file
     *
     * @mbg.generated
     */
    private String sFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.s_id
     *
     * @return the value of stu.s_id
     *
     * @mbg.generated
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.s_id
     *
     * @param sId the value for stu.s_id
     *
     * @mbg.generated
     */
    public void setsId(String sId) {
        this.sId = sId == null ? null : sId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.s_name
     *
     * @return the value of stu.s_name
     *
     * @mbg.generated
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.s_name
     *
     * @param sName the value for stu.s_name
     *
     * @mbg.generated
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.s_sex
     *
     * @return the value of stu.s_sex
     *
     * @mbg.generated
     */
    public String getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.s_sex
     *
     * @param sSex the value for stu.s_sex
     *
     * @mbg.generated
     */
    public void setsSex(String sSex) {
        this.sSex = sSex == null ? null : sSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.s_education
     *
     * @return the value of stu.s_education
     *
     * @mbg.generated
     */
    public String getsEducation() {
        return sEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.s_education
     *
     * @param sEducation the value for stu.s_education
     *
     * @mbg.generated
     */
    public void setsEducation(String sEducation) {
        this.sEducation = sEducation == null ? null : sEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.s_salary
     *
     * @return the value of stu.s_salary
     *
     * @mbg.generated
     */
    public BigDecimal getsSalary() {
        return sSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.s_salary
     *
     * @param sSalary the value for stu.s_salary
     *
     * @mbg.generated
     */
    public void setsSalary(BigDecimal sSalary) {
        this.sSalary = sSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.s_file
     *
     * @return the value of stu.s_file
     *
     * @mbg.generated
     */
    public String getsFile() {
        return sFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.s_file
     *
     * @param sFile the value for stu.s_file
     *
     * @mbg.generated
     */
    public void setsFile(String sFile) {
        this.sFile = sFile == null ? null : sFile.trim();
    }
}